#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
生成 MES 完整数据库架构（基于 MFGID 为最小追溯单位）
"""

import os

OUTPUT_FILE = os.path.join(os.path.dirname(__file__), 'mes_complete_schema.md')

lines = []

def L(line=''):
    lines.append(line)

def write():
    L('## 完整数据库架构设计（MFGID 为最小追溯单位）')
    L('')
    L('### 架构设计原则')
    L('')
    L('1. **批次层级管理**：Wafer Lot → Mother Lot → Sub Lot → Grade Lot → MFGID')
    L('2. **MFGID 为最小追溯单位**：Reel/Tape Level，ERP 财务核算基础')
    L('3. **批次与 MFGID 分离**：Lot 是管理单位，MFGID 是追溯单位')
    L('4. **完整追溯链**：从 MFGID 可以追溯到 Wafer Lot、工单、产品、客户')
    L('5. **Hold 维度扩展**：支持 9 种 Hold 维度（PO/WaferLot/Product/Package/Equipment/Step/Bin/Lot/Route）')
    L('')
    L('### 表分类')
    L('')
    L('| 分类 | 表数量 | 说明 |')
    L('|------|--------|------|')
    L('| 系统基础表 | 7 | 部门、角色、用户、权限、签名等 |')
    L('| 主数据表 | 8 | 产品、路线、工序、设备、载具、配方等 |')
    L('| **来料管理表** | **3** | **Wafer Lot、Wafer Map、IQC 检验（新增）** |')
    L('| 批次管理表 | 1 | ProdLot（原有，需扩展字段） |')
    L('| 批次步骤表 | 1 | ProdLotStep（原有） |')
    L('| 操作历史表 | 2 | OperationHistory、AuditTrail（原有） |')
    L('| Hold 管理表 | 2 | HoldRecord（扩展）、AutoHoldRule（新增） |')
    L('| 追溯链表 | 2 | LotTraceChain（新增）、LotSplit/Merge（原有） |')
    L('| **MFGID 表** | **3** | **MfgUnit、MfgOperationHistory、MfgPackTrace（新增）** |')
    L('| 工单管理表 | 1 | WorkOrder（原有） |')
    L('| 质量门表 | 3 | QualityGate、Inspection、GateInstance（原有） |')
    L('| 物料管理表 | 3 | Material、Requirement、Consume（原有） |')
    L('| 报表归档表 | 4 | DailyReport、LotArchive、SystemEvent、Config（原有） |')
    L('| 外部系统表 | 2 | SystemEvent、Config（原有） |')
    L('')
    L('总计：**42 张表**（新增 6 张，修改 2 张，删除 0 张）')
    L('')
    L('---')
    L('')
    L('### 一、系统基础表（7 张）')
    L('')
    L('```sql')
    L('-- 1.1 部门表')
    L('CREATE TABLE `sys_department` (')
    L('  `dept_id` VARCHAR(50) PRIMARY KEY,')
    L('  `dept_name` VARCHAR(100) NOT NULL,')
    L('  `parent_id` VARCHAR(50) DEFAULT NULL,')
    L('  `manager_id` VARCHAR(50) DEFAULT NULL,')
    L('  `status` VARCHAR(20) DEFAULT \'Active\',')
    L('  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP')
    L(') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;')
    L('')
    L('-- 1.2 角色表')
    L('CREATE TABLE `sys_role` (')
    L('  `role_id` VARCHAR(50) PRIMARY KEY,')
    L('  `role_name` VARCHAR(100) NOT NULL,')
    L('  `description` VARCHAR(255) DEFAULT NULL,')
    L('  `level` INT DEFAULT 0,')
    L('  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP')
    L(') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;')
    L('')
    L('-- 1.3 用户表')
    L('CREATE TABLE `sys_user` (')
    L('  `user_id` VARCHAR(50) PRIMARY KEY,')
    L('  `user_name` VARCHAR(100) NOT NULL,')
    L('  `password_hash` VARCHAR(255) NOT NULL,')
    L('  `role_id` VARCHAR(50) NOT NULL,')
    L('  `dept_id` VARCHAR(50) NOT NULL,')
    L('  `shift` VARCHAR(20) DEFAULT \'A\',')
    L('  `is_active` TINYINT(1) DEFAULT 1,')
    L('  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,')
    L('  FOREIGN KEY (`role_id`) REFERENCES `sys_role`(`role_id`),')
    L('  FOREIGN KEY (`dept_id`) REFERENCES `sys_department`(`dept_id`)')
    L(') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;')
    L('')
    L('-- 1.4 用户权限表')
    L('CREATE TABLE `sys_user_permission` (')
    L('  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,')
    L('  `user_id` VARCHAR(50) NOT NULL,')
    L('  `permission_code` VARCHAR(100) NOT NULL,')
    L('  `granted_at` DATETIME DEFAULT CURRENT_TIMESTAMP,')
    L('  UNIQUE KEY `uk_user_permission` (`user_id`, `permission_code`)')
    L(') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;')
    L('')
    L('-- 1.5 签名等级表')
    L('CREATE TABLE `sys_signature_level` (')
    L('  `level_id` VARCHAR(50) PRIMARY KEY,')
    L('  `level_name` VARCHAR(100) NOT NULL,')
    L('  `required_role` VARCHAR(50) NOT NULL,')
    L('  `min_level` INT NOT NULL,')
    L('  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP')
    L(') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;')
    L('')
    L('-- 1.6 电子签名表')
    L('CREATE TABLE `sys_signature` (')
    L('  `signature_id` VARCHAR(50) PRIMARY KEY,')
    L('  `user_id` VARCHAR(50) NOT NULL,')
    L('  `password_hash` VARCHAR(255) NOT NULL,')
    L('  `level_id` VARCHAR(50) NOT NULL,')
    L('  `is_active` TINYINT(1) DEFAULT 1,')
    L('  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,')
    L('  FOREIGN KEY (`user_id`) REFERENCES `sys_user`(`user_id`),')
    L('  FOREIGN KEY (`level_id`) REFERENCES `sys_signature_level`(`level_id`)')
    L(') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;')
    L('')
    L('-- 1.7 系统配置表')
    L('CREATE TABLE `sys_config` (')
    L('  `config_key` VARCHAR(100) PRIMARY KEY,')
    L('  `config_value` TEXT NOT NULL,')
    L('  `description` VARCHAR(255) DEFAULT NULL,')
    L('  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,')
    L('  `updated_by` VARCHAR(50) DEFAULT NULL')
    L(') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;')
    L('```')
    L('')
    L('### 二、主数据表（8 张）')
    L('')
    L('```sql')
    L('-- 2.1 产品表')
    L('CREATE TABLE `master_product` (')
    L('  `product_id` VARCHAR(50) PRIMARY KEY,')
    L('  `product_name` VARCHAR(100) NOT NULL,')
    L('  `die_name` VARCHAR(100) DEFAULT NULL,')
    L('  `package_type` VARCHAR(50) NOT NULL,')
    L('  `customer_id` VARCHAR(50) DEFAULT NULL,')
    L('  `customer_name` VARCHAR(100) DEFAULT NULL,')
    L('  `customer_pn` VARCHAR(100) DEFAULT NULL,')
    L('  `internal_pn` VARCHAR(100) DEFAULT NULL,')
    L('  `status` VARCHAR(20) DEFAULT \'Active\',')
    L('  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP')
    L(') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;')
    L('')
    L('-- 2.2 工艺路线表')
    L('CREATE TABLE `master_route` (')
    L('  `route_id` VARCHAR(100) PRIMARY KEY,')
    L('  `route_name` VARCHAR(100) NOT NULL,')
    L('  `route_version` VARCHAR(20) DEFAULT \'1.0\',')
    L('  `product_id` VARCHAR(50) DEFAULT NULL,')
    L('  `package_type` VARCHAR(50) NOT NULL,')
    L('  `route_type` VARCHAR(20) DEFAULT \'Normal\' COMMENT \'Normal/Rework\',')
    L('  `is_active` TINYINT(1) DEFAULT 1,')
    L('  `is_approved` TINYINT(1) DEFAULT 0,')
    L('  `approved_by` VARCHAR(50) DEFAULT NULL,')
    L('  `approved_at` DATETIME DEFAULT NULL,')
    L('  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP')
    L(') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;')
    L('')
    L('-- 2.3 工艺路线工序表')
    L('CREATE TABLE `master_route_step` (')
    L('  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,')
    L('  `route_id` VARCHAR(100) NOT NULL,')
    L('  `step_seq` INT NOT NULL,')
    L('  `step_code` VARCHAR(50) NOT NULL,')
    L('  `step_name` VARCHAR(100) NOT NULL,')
    L('  `equipment_group` VARCHAR(50) NOT NULL,')
    L('  `is_rework` TINYINT(1) DEFAULT 0,')
    L('  `is_critical` TINYINT(1) DEFAULT 0,')
    L('  `is_key_process` TINYINT(1) DEFAULT 0,')
    L('  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,')
    L('  UNIQUE KEY `uk_route_step` (`route_id`, `step_seq`)')
    L(') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;')
    L('')
    L('-- 2.4 设备表')
    L('CREATE TABLE `master_equipment` (')
    L('  `equipment_id` VARCHAR(50) PRIMARY KEY,')
    L('  `equipment_name` VARCHAR(100) NOT NULL,')
    L('  `equipment_group` VARCHAR(50) NOT NULL,')
    L('  `equipment_type` VARCHAR(50) NOT NULL,')
    L('  `status` VARCHAR(20) DEFAULT \'Available\',')
    L('  `location` VARCHAR(100) DEFAULT NULL,')
    L('  `responsible_person` VARCHAR(50) DEFAULT NULL,')
    L('  `last_maintenance_date` DATETIME DEFAULT NULL,')
    L('  `maintenance_interval_hours` INT DEFAULT 500,')
    L('  `running_hours` INT DEFAULT 0,')
    L('  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP')
    L(') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;')
    L('')
    L('-- 2.5 设备路线关联表')
    L('CREATE TABLE `master_equipment_route` (')
    L('  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,')
    L('  `equipment_id` VARCHAR(50) NOT NULL,')
    L('  `route_id` VARCHAR(100) NOT NULL,')
    L('  `step_code` VARCHAR(50) NOT NULL,')
    L('  `is_qualified` TINYINT(1) DEFAULT 1,')
    L('  `qualified_at` DATETIME DEFAULT NULL,')
    L('  `qualified_by` VARCHAR(50) DEFAULT NULL,')
    L('  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,')
    L('  UNIQUE KEY `uk_equipment_route_step` (`equipment_id`, `route_id`, `step_code`)')
    L(') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;')
    L('')
    L('-- 2.6 载具表')
    L('CREATE TABLE `master_carrier` (')
    L('  `carrier_id` VARCHAR(50) PRIMARY KEY,')
    L('  `carrier_type` VARCHAR(50) NOT NULL,')
    L('  `carrier_name` VARCHAR(100) NOT NULL,')
    L('  `max_capacity` INT NOT NULL,')
    L('  `status` VARCHAR(20) DEFAULT \'Available\',')
    L('  `location` VARCHAR(100) DEFAULT NULL,')
    L('  `last_calibration_date` DATETIME DEFAULT NULL,')
    L('  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP')
    L(') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;')
    L('')
    L('-- 2.7 配方表')
    L('CREATE TABLE `master_recipe` (')
    L('  `recipe_id` VARCHAR(100) PRIMARY KEY,')
    L('  `recipe_name` VARCHAR(100) NOT NULL,')
    L('  `product_id` VARCHAR(50) DEFAULT NULL,')
    L('  `route_id` VARCHAR(100) DEFAULT NULL,')
    L('  `step_code` VARCHAR(50) NOT NULL,')
    L('  `equipment_id` VARCHAR(50) NOT NULL,')
    L('  `version` VARCHAR(20) DEFAULT \'1.0\',')
    L('  `is_active` TINYINT(1) DEFAULT 1,')
    L('  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP')
    L(') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;')
    L('')
    L('-- 2.8 良率规则表')
    L('CREATE TABLE `master_yield_rule` (')
    L('  `rule_id` VARCHAR(50) PRIMARY KEY,')
    L('  `rule_name` VARCHAR(100) NOT NULL,')
    L('  `product_id` VARCHAR(50) DEFAULT NULL,')
    L('  `step_code` VARCHAR(50) DEFAULT NULL,')
    L('  `yield_threshold` DECIMAL(5,2) NOT NULL,')
    L('  `action` VARCHAR(50) NOT NULL COMMENT \'Hold/Alarm/Notify\',')
    L('  `is_active` TINYINT(1) DEFAULT 1,')
    L('  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP')
    L(') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;')
    L('```')
    L('')
    L('### 三、来料管理表（新增 3 张）')
    L('')
    L('```sql')
    L('-- 3.1 来料晶圆批次表（新增）')
    L('CREATE TABLE `wafer_lot` (')
    L('  `wafer_lot_id` VARCHAR(50) PRIMARY KEY COMMENT \'来料批次号：WF-YYYYMMDD-NNN\',')
    L('  `wafer_id` VARCHAR(50) NOT NULL COMMENT \'晶圆 ID\',')
    L('  `wafer_fab` VARCHAR(100) DEFAULT \'\' COMMENT \'晶圆厂\',')
    L('  `wafer_size` VARCHAR(20) DEFAULT \'\' COMMENT \'晶圆尺寸：6inch/8inch/12inch\',')
    L('  `total_die_count` INT DEFAULT 0 COMMENT \'总 Die 数量\',')
    L('  `good_die_count` INT DEFAULT 0 COMMENT \'良品 Die 数量 (根据 Wafer Map)\',')
    L('  `product_id` VARCHAR(50) DEFAULT \'\' COMMENT \'产品 ID\',')
    L('  `order_id` VARCHAR(50) DEFAULT \'\' COMMENT \'关联工单号\',')
    L('  `status` VARCHAR(20) DEFAULT \'Received\' COMMENT \'状态：Received/Inspected/Released/Consumed\',')
    L('  `iqc_result` VARCHAR(20) DEFAULT \'\' COMMENT \'IQC 检验结果：Pass/Fail/Pending\',')
    L('  `iqc_inspector` VARCHAR(50) DEFAULT \'\' COMMENT \'IQC 检验员\',')
    L('  `iqc_inspected_at` DATETIME NULL COMMENT \'IQC 检验时间\',')
    L('  `released_at` DATETIME NULL COMMENT \'释放到生产的时间\',')
    L('  `consumed_at` DATETIME NULL COMMENT \'全部消耗完成时间\',')
    L('  `remark` VARCHAR(500) DEFAULT \'\' COMMENT \'备注\',')
    L('  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,')
    L('  `created_by` VARCHAR(50) DEFAULT \'\',')
    L('  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,')
    L('  `updated_by` VARCHAR(50) DEFAULT \'\'')
    L(') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT=\'来料晶圆批次表\';')
    L('')
    L('CREATE INDEX `idx_wafer_lot_status` ON `wafer_lot`(`status`);')
    L('CREATE INDEX `idx_wafer_lot_product` ON `wafer_lot`(`product_id`);')
    L('CREATE INDEX `idx_wafer_lot_order` ON `wafer_lot`(`order_id`);')
    L('')
    L('-- 3.2 Wafer Map 表（新增）')
    L('CREATE TABLE `wafer_map` (')
    L('  `map_id` VARCHAR(50) PRIMARY KEY COMMENT \'Map ID\',')
    L('  `wafer_lot_id` VARCHAR(50) NOT NULL COMMENT \'来料批次号\',')
    L('  `wafer_id` VARCHAR(50) NOT NULL COMMENT \'晶圆 ID\',')
    L('  `map_data` JSON COMMENT \'Map 数据：JSON 格式存储每个 Die 的坐标和状态\',')
    L('  `total_die` INT DEFAULT 0 COMMENT \'总 Die 数\',')
    L('  `good_die` INT DEFAULT 0 COMMENT \'良品 Die 数\',')
    L('  `bad_die` INT DEFAULT 0 COMMENT \'不良 Die 数\',')
    L('  `map_format` VARCHAR(20) DEFAULT \'\' COMMENT \'Map 格式：CSV/XML/JSON\',')
    L('  `imported_by` VARCHAR(50) DEFAULT \'\' COMMENT \'导入人\',')
    L('  `imported_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT \'导入时间\',')
    L('  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP')
    L(') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT=\'Wafer Map 表\';')
    L('')
    L('CREATE INDEX `idx_wafer_map_lot` ON `wafer_map`(`wafer_lot_id`);')
    L('')
    L('-- 3.3 来料检验记录表（新增）')
    L('CREATE TABLE `incoming_inspection` (')
    L('  `inspection_id` VARCHAR(50) PRIMARY KEY COMMENT \'检验记录 ID\',')
    L('  `wafer_lot_id` VARCHAR(50) NOT NULL COMMENT \'来料批次号\',')
    L('  `inspection_type` VARCHAR(20) DEFAULT \'IQC\' COMMENT \'检验类型：IQC/IPQC/OQC\',')
    L('  `inspection_result` VARCHAR(20) DEFAULT \'\' COMMENT \'检验结果：Pass/Fail/Conditional\',')
    L('  `defect_code` VARCHAR(50) DEFAULT \'\' COMMENT \'缺陷代码\',')
    L('  `defect_description` VARCHAR(500) DEFAULT \'\' COMMENT \'缺陷描述\',')
    L('  `inspector_id` VARCHAR(50) DEFAULT \'\' COMMENT \'检验员 ID\',')
    L('  `inspector_name` VARCHAR(50) DEFAULT \'\' COMMENT \'检验员姓名\',')
    L('  `inspected_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT \'检验时间\',')
    L('  `remark` VARCHAR(500) DEFAULT \'\' COMMENT \'备注\',')
    L('  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP')
    L(') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT=\'来料检验记录表\';')
    L('')
    L('CREATE INDEX `idx_incoming_inspection_lot` ON `incoming_inspection`(`wafer_lot_id`);')
    L('```')
    L('')
    L('### 四、批次管理表（修改 1 张）')
    L('')
    L('```sql')
    L('-- 4.1 批次表（扩展字段）')
    L('CREATE TABLE `prod_lot` (')
    L('  -- === 基础字段（保留原有）===')
    L('  `lot_id` VARCHAR(50) NOT NULL,')
    L('  `order_id` VARCHAR(50) NOT NULL,')
    L('  `product_id` VARCHAR(50) NOT NULL,')
    L('  `product_name` VARCHAR(100) NOT NULL,')
    L('  `die_name` VARCHAR(100) DEFAULT NULL,')
    L('  `package_type` VARCHAR(50) NOT NULL,')
    L('  `route_id` VARCHAR(100) NOT NULL,')
    L('  `route_version` VARCHAR(20) NOT NULL DEFAULT \'1.0\',')
    L('  `current_step_seq` INT NOT NULL DEFAULT 0,')
    L('  `current_step_code` VARCHAR(50) DEFAULT NULL,')
    L('  `status` VARCHAR(20) NOT NULL DEFAULT \'Waiting\',')
    L('  `unit_count` INT NOT NULL DEFAULT 0,')
    L('  `strip_count` INT NOT NULL DEFAULT 0,')
    L('  `priority` VARCHAR(20) NOT NULL DEFAULT \'Normal\',')
    L('  `carrier_type` VARCHAR(50) DEFAULT NULL,')
    L('  `carrier_id` VARCHAR(50) DEFAULT NULL,')
    L('  `wafer_lot_id` VARCHAR(50) DEFAULT NULL,')
    L('  ')
    L('  -- === 新增批次层级字段 ===')
    L('  `lot_level` VARCHAR(20) DEFAULT \'Mother\' COMMENT \'批次层级：Wafer/Mother/Sub/Grade\',')
    L('  `lot_hierarchy_path` VARCHAR(500) DEFAULT \'\' COMMENT \'层级路径：如 "WF-20260526-001/LOT-20260001/LOT-20260001-T1"\',')
    L('  `root_wafer_lot_id` VARCHAR(50) DEFAULT \'\' COMMENT \'根晶圆批次 ID\',')
    L('  `process_stage` VARCHAR(20) DEFAULT \'Assemble\' COMMENT \'工艺阶段：Assemble/Test/Finished\',')
    L('  `mother_lot_id` VARCHAR(50) DEFAULT NULL COMMENT \'母批次 ID\',')
    L('  ')
    L('  -- === 新增数量字段 ===')
    L('  `original_qty` INT NOT NULL DEFAULT 0 COMMENT \'原始数量\',')
    L('  `total_pass_qty` INT NOT NULL DEFAULT 0 COMMENT \'累计合格数量\',')
    L('  `total_scrap_qty` INT NOT NULL DEFAULT 0 COMMENT \'累计报废数量\',')
    L('  `total_rework_qty` INT NOT NULL DEFAULT 0 COMMENT \'累计重工数量\',')
    L('  `total_hold_qty` INT NOT NULL DEFAULT 0 COMMENT \'累计 Hold 数量\',')
    L('  ')
    L('  -- === 新增 Grade/Bin 字段 ===')
    L('  `bin_result` VARCHAR(50) DEFAULT NULL COMMENT \'Bin 结果\',')
    L('  `grade` VARCHAR(20) DEFAULT NULL COMMENT \'等级：A/B/C\',')
    L('  `test_result` VARCHAR(50) DEFAULT NULL COMMENT \'测试结果\',')
    L('  `qty_pass` INT NOT NULL DEFAULT 0 COMMENT \'良品数\',')
    L('  `qty_fail` INT NOT NULL DEFAULT 0 COMMENT \'不良数\',')
    L('  ')
    L('  -- === 新增重工字段 ===')
    L('  `is_rework_lot` TINYINT(1) NOT NULL DEFAULT 0,')
    L('  `original_route_id` VARCHAR(100) DEFAULT NULL,')
    L('  `rework_route_id` VARCHAR(100) DEFAULT NULL,')
    L('  `rework_count` INT DEFAULT NULL,')
    L('  `rework_reason` VARCHAR(255) DEFAULT NULL,')
    L('  ')
    L('  -- === 新增 MRB 字段 ===')
    L('  `is_under_mrb` TINYINT(1) NOT NULL DEFAULT 0,')
    L('  `mrb_reference` VARCHAR(50) DEFAULT NULL,')
    L('  `mrb_disposition` VARCHAR(50) DEFAULT NULL,')
    L('  ')
    L('  -- === 新增时间字段 ===')
    L('  `completed_at` DATETIME NULL COMMENT \'完成时间\',')
    L('  `in_warehouse_at` DATETIME NULL COMMENT \'入库时间\',')
    L('  `shipped_at` DATETIME NULL COMMENT \'出货时间\',')
    L('  ')
    L('  -- === 原有字段（保留）===')
    L('  `is_partial_lot` TINYINT(1) NOT NULL DEFAULT 0,')
    L('  `split_reason` VARCHAR(255) DEFAULT NULL,')
    L('  `split_time` DATETIME DEFAULT NULL,')
    L('  `split_qty` INT DEFAULT NULL,')
    L('  `hold_category` VARCHAR(50) DEFAULT NULL,')
    L('  `hold_reason` VARCHAR(255) DEFAULT NULL,')
    L('  `hold_time` DATETIME DEFAULT NULL,')
    L('  `hold_operator` VARCHAR(50) DEFAULT NULL,')
    L('  `release_condition` VARCHAR(255) DEFAULT NULL,')
    L('  `is_archived` TINYINT(1) NOT NULL DEFAULT 0,')
    L('  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,')
    L('  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,')
    L('  ')
    L('  PRIMARY KEY (`lot_id`),')
    L('  INDEX `idx_order_id` (`order_id`),')
    L('  INDEX `idx_product_id` (`product_id`),')
    L('  INDEX `idx_status` (`status`),')
    L('  INDEX `idx_current_step` (`current_step_code`),')
    L('  INDEX `idx_lot_level` (`lot_level`),')
    L('  INDEX `idx_root_wafer_lot` (`root_wafer_lot_id`),')
    L('  INDEX `idx_process_stage` (`process_stage`),')
    L('  INDEX `idx_mother_lot` (`mother_lot_id`),')
    L('  INDEX `idx_created_at` (`created_at`)')
    L(') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT=\'生产批次表\';')
    L('```')
    L('')
    L('### 五、MFGID 表（新增 3 张）')
    L('')
    L('```sql')
    L('-- 5.1 MFG 最小追溯单位表（新增）')
    L('CREATE TABLE `mfg_unit` (')
    L('  `mfg_id` VARCHAR(50) PRIMARY KEY COMMENT \'MFGID: 最小追溯单位唯一标识\',')
    L('  `lot_id` VARCHAR(50) NOT NULL COMMENT \'当前所属批次 ID\',')
    L('  `root_wafer_lot_id` VARCHAR(50) NOT NULL COMMENT \'根晶圆批次 ID\',')
    L('  `wafer_id` VARCHAR(50) DEFAULT \'\' COMMENT \'晶圆 ID\',')
    L('  `die_x` INT DEFAULT -1 COMMENT \'Die X 坐标\',')
    L('  `die_y` INT DEFAULT -1 COMMENT \'Die Y 坐标\',')
    L('  `serial_number` VARCHAR(50) DEFAULT \'\' COMMENT \'序列号\',')
    L('  `reel_id` VARCHAR(50) DEFAULT \'\' COMMENT \'卷带编号\',')
    L('  `reel_capacity` INT DEFAULT 0 COMMENT \'卷带容量\',')
    L('  `actual_qty` INT DEFAULT 0 COMMENT \'实际数量\',')
    L('  `status` VARCHAR(20) DEFAULT \'Created\' COMMENT \'状态：Created/Processing/Completed/Scrapped/Shipped\',')
    L('  `grade` VARCHAR(10) DEFAULT \'\' COMMENT \'等级：A/B/C\',')
    L('  `bin_result` VARCHAR(20) DEFAULT \'\' COMMENT \'Bin 结果\',')
    L('  `current_step` VARCHAR(50) DEFAULT \'\' COMMENT \'当前工序\',')
    L('  `rework_count` INT DEFAULT 0 COMMENT \'重工次数\',')
    L('  `pack_time` DATETIME NULL COMMENT \'包装时间\',')
    L('  `packed_by` VARCHAR(50) DEFAULT \'\' COMMENT \'包装操作员\',')
    L('  `box_id` VARCHAR(50) DEFAULT \'\' COMMENT \'绑定到的 Box ID\',')
    L('  `pallet_id` VARCHAR(50) DEFAULT \'\' COMMENT \'绑定到的 Pallet ID\',')
    L('  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,')
    L('  `completed_at` DATETIME NULL COMMENT \'完成时间\',')
    L('  `shipped_at` DATETIME NULL COMMENT \'出货时间\',')
    L('  INDEX `idx_lot_id` (`lot_id`),')
    L('  INDEX `idx_root_wafer_lot` (`root_wafer_lot_id`),')
    L('  INDEX `idx_status` (`status`),')
    L('  INDEX `idx_grade` (`grade`),')
    L('  INDEX `idx_reel_id` (`reel_id`)')
    L(') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT=\'MFG 最小追溯单位表\';')
    L('')
    L('-- 5.2 MFG 操作历史表（新增）')
    L('CREATE TABLE `mfg_operation_history` (')
    L('  `history_id` VARCHAR(50) PRIMARY KEY,')
    L('  `mfg_id` VARCHAR(50) NOT NULL COMMENT \'MFGID\',')
    L('  `lot_id` VARCHAR(50) NOT NULL COMMENT \'批次 ID\',')
    L('  `step_code` VARCHAR(50) NOT NULL COMMENT \'工序代码\',')
    L('  `operation` VARCHAR(20) COMMENT \'操作：TrackIn/TrackOut/Hold/Release/Rework/Scrap\',')
    L('  `equipment_id` VARCHAR(50) DEFAULT \'\' COMMENT \'设备 ID\',')
    L('  `operator_id` VARCHAR(50) DEFAULT \'\' COMMENT \'操作员\',')
    L('  `result` VARCHAR(20) DEFAULT \'\' COMMENT \'结果：Pass/Fail\',')
    L('  `test_data` JSON COMMENT \'测试数据\',')
    L('  `remark` VARCHAR(500) DEFAULT \'\',')
    L('  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,')
    L('  INDEX `idx_mfg_id` (`mfg_id`),')
    L('  INDEX `idx_lot_id` (`lot_id`),')
    L('  INDEX `idx_step_code` (`step_code`)')
    L(') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT=\'MFG 操作历史表\';')
    L('')
    L('-- 5.3 MFG 包装追溯表（新增）')
    L('CREATE TABLE `mfg_pack_trace` (')
    L('  `pack_trace_id` VARCHAR(50) PRIMARY KEY,')
    L('  `mfg_id` VARCHAR(50) NOT NULL COMMENT \'MFGID\',')
    L('  `pack_level` VARCHAR(20) COMMENT \'包装层级：Unit/Reel/Box/Pallet\',')
    L('  `pack_id` VARCHAR(50) COMMENT \'包装 ID\',')
    L('  `parent_pack_id` VARCHAR(50) DEFAULT \'\' COMMENT \'父包装 ID\',')
    L('  `pack_qty` INT DEFAULT 0 COMMENT \'包装数量\',')
    L('  `packed_at` DATETIME DEFAULT CURRENT_TIMESTAMP,')
    L('  `packed_by` VARCHAR(50) DEFAULT \'\' COMMENT \'包装操作员\',')
    L('  INDEX `idx_mfg_id` (`mfg_id`),')
    L('  INDEX `idx_pack_id` (`pack_id`)')
    L(') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT=\'MFG 包装追溯表\';')
    L('```')
    L('')
    L('### 六、Hold 管理表（扩展 1 张，新增 1 张）')
    L('')
    L('```sql')
    L('-- 6.1 Hold 记录表（扩展字段）')
    L('CREATE TABLE `prod_hold_record` (')
    L('  -- === 原有字段（保留）===')
    L('  `hold_id` VARCHAR(50) NOT NULL,')
    L('  `lot_id` VARCHAR(50) NOT NULL,')
    L('  `hold_type` VARCHAR(50) NOT NULL,')
    L('  `hold_reason_code` VARCHAR(50) DEFAULT NULL,')
    L('  `hold_reason` VARCHAR(255) NOT NULL,')
    L('  `hold_qty` INT NOT NULL,')
    L('  `responsible_dept` VARCHAR(50) DEFAULT NULL,')
    L('  `owner` VARCHAR(50) DEFAULT NULL,')
    L('  `status` VARCHAR(20) NOT NULL DEFAULT \'Open\',')
    L('  `hold_by` VARCHAR(50) NOT NULL,')
    L('  `hold_time` DATETIME NOT NULL,')
    L('  `root_cause` TEXT DEFAULT NULL,')
    L('  `corrective_action` TEXT DEFAULT NULL,')
    L('  `disposition` VARCHAR(255) DEFAULT NULL,')
    L('  `release_by` VARCHAR(50) DEFAULT NULL,')
    L('  `release_time` DATETIME DEFAULT NULL,')
    L('  `release_comment` TEXT DEFAULT NULL,')
    L('  `approved_by` VARCHAR(50) DEFAULT NULL,')
    L('  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,')
    L('  ')
    L('  -- === 新增 Hold 维度字段 ===')
    L('  `hold_scope` VARCHAR(20) DEFAULT \'Lot\' COMMENT \'Hold 范围：WorkOrder/WaferLot/Product/Package/Equipment/Step/Bin/Lot/Route\',')
    L('  `scope_id` VARCHAR(50) DEFAULT \'\' COMMENT \'范围 ID：根据 HoldScope 存储对应的 ID\',')
    L('  `hold_priority` INT DEFAULT 9 COMMENT \'Hold 优先级：1(PO Hold) ~ 9(Lot Hold)\',')
    L('  `is_cascade` TINYINT(1) DEFAULT 0 COMMENT \'是否级联 Hold\',')
    L('  ')
    L('  PRIMARY KEY (`hold_id`),')
    L('  INDEX `idx_lot_id` (`lot_id`),')
    L('  INDEX `idx_status` (`status`),')
    L('  INDEX `idx_hold_scope` (`hold_scope`),')
    L('  INDEX `idx_scope_id` (`scope_id`),')
    L('  INDEX `idx_hold_priority` (`hold_priority`)')
    L(') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;')
    L('')
    L('-- 6.2 自动 Hold 规则表（新增）')
    L('CREATE TABLE `auto_hold_rule` (')
    L('  `rule_id` VARCHAR(50) PRIMARY KEY COMMENT \'规则 ID\',')
    L('  `rule_name` VARCHAR(100) NOT NULL COMMENT \'规则名称\',')
    L('  `rule_type` VARCHAR(20) DEFAULT \'\' COMMENT \'规则类型：Yield/Equipment/Quality/Step\',')
    L('  `hold_scope` VARCHAR(20) DEFAULT \'Lot\' COMMENT \'Hold 范围\',')
    L('  `trigger_condition` JSON COMMENT \'触发条件：JSON 格式\',')
    L('  `hold_reason_code` VARCHAR(50) DEFAULT \'\' COMMENT \'Hold 原因代码\',')
    L('  `hold_reason` VARCHAR(500) DEFAULT \'\' COMMENT \'Hold 原因\',')
    L('  `auto_release` TINYINT(1) DEFAULT 0 COMMENT \'是否自动释放\',')
    L('  `auto_release_condition` JSON COMMENT \'自动释放条件\',')
    L('  `is_active` TINYINT(1) DEFAULT 1 COMMENT \'是否启用\',')
    L('  `priority` INT DEFAULT 5 COMMENT \'优先级：1-10\',')
    L('  `created_by` VARCHAR(50) DEFAULT \'\',')
    L('  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,')
    L('  `updated_by` VARCHAR(50) DEFAULT \'\',')
    L('  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,')
    L('  INDEX `idx_rule_type` (`rule_type`),')
    L('  INDEX `idx_active` (`is_active`)')
    L(') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT=\'自动 Hold 规则表\';')
    L('```')
    L('')
    L('### 七、追溯链表（新增 1 张，保留 2 张）')
    L('')
    L('```sql')
    L('-- 7.1 批次追溯链表（新增）')
    L('CREATE TABLE `lot_trace_chain` (')
    L('  `chain_id` VARCHAR(50) PRIMARY KEY COMMENT \'追溯链 ID\',')
    L('  `child_lot_id` VARCHAR(50) NOT NULL COMMENT \'子批次 ID\',')
    L('  `parent_lot_id` VARCHAR(50) NOT NULL COMMENT \'父批次 ID\',')
    L('  `relation_type` VARCHAR(20) DEFAULT \'\' COMMENT \'关系类型：Split/Merge/GradeSplit/Rework/AssembleToTest\',')
    L('  `split_qty` INT DEFAULT 0 COMMENT \'拆分数量\',')
    L('  `merge_source_lot_ids` VARCHAR(500) DEFAULT \'\' COMMENT \'合并源批次 ID 列表\',')
    L('  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,')
    L('  `created_by` VARCHAR(50) DEFAULT \'\',')
    L('  INDEX `idx_child_lot` (`child_lot_id`),')
    L('  INDEX `idx_parent_lot` (`parent_lot_id`)')
    L(') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT=\'批次追溯链表\';')
    L('')
    L('-- 7.2 批次拆分记录表（保留原有）')
    L('-- 7.3 批次合并记录表（保留原有）')
    L('```')
    L('')
    L('### 八、其他表（保留原有）')
    L('')
    L('保留以下原有表（不修改）：')
    L('- `prod_work_order` 工单表')
    L('- `prod_lot_step` 批次步骤表')
    L('- `prod_operation_history` 操作历史表')
    L('- `prod_audit_trail` 审计追踪表')
    L('- `prod_scrap_record` 报废记录表')
    L('- `prod_rework_record` 重工记录表')
    L('- `prod_lot_merge` 批次合并表')
    L('- `prod_genealogy` 批次族谱表')
    L('- `prod_carrier_binding` 载具绑定表')
    L('- `prod_dispatch_task` 调度任务表')
    L('- `quality_gate` 质量门表')
    L('- `quality_inspection` 质量检验表')
    L('- `quality_gate_instance` 质量门实例表')
    L('- `alarm_rule` 告警规则表')
    L('- `alarm_record` 告警记录表')
    L('- `customer_requirement` 客户需求表')
    L('- `report_production_daily` 生产日报表')
    L('- `prod_lot_archive` 批次归档表')
    L('- `ext_system_event` 外部系统事件表')
    L('- `ext_system_config` 外部系统配置表')
    L('- `master_material` 物料主数据表')
    L('- `material_requirement` 物料需求表')
    L('- `material_consume` 物料消耗表')
    L('- `prod_signature` 生产签名表')
    L('- `quantity_transaction` 数量交易表')
    L('')
    L('---')
    L('')
    L('### 总结')
    L('')
    L('| 分类 | 原有表数 | 新增表数 | 修改表数 | 删除表数 | 最终表数 |')
    L('|------|---------|---------|---------|---------|---------|')
    L('| 系统基础表 | 7 | 0 | 0 | 0 | 7 |')
    L('| 主数据表 | 8 | 0 | 0 | 0 | 8 |')
    L('| 来料管理表 | 0 | 3 | 0 | 0 | 3 |')
    L('| 批次管理表 | 1 | 0 | 1 | 0 | 1 |')
    L('| MFGID 表 | 0 | 3 | 0 | 0 | 3 |')
    L('| Hold 管理表 | 1 | 1 | 1 | 0 | 2 |')
    L('| 追溯链表 | 2 | 1 | 0 | 0 | 3 |')
    L('| 其他表 | 24 | 0 | 0 | 0 | 24 |')
    L('| **总计** | **43** | **8** | **2** | **0** | **51** |')
    L('')
    L('注：原 `prod_lot` 表扩展字段，`prod_hold_record` 表扩展字段，其他表保持不变。')
    L('')

    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    
    print(f'Generated: {OUTPUT_FILE}')
    print(f'Lines: {len(lines)}')

if __name__ == '__main__':
    write()
