#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
生成 MES 方案文档 - 完整数据库架构章节
"""

import os

OUTPUT_FILE = os.path.join(os.path.dirname(__file__), '..', 'mes_db_architecture.md')

lines = []

def L(line=''):
    lines.append(line)

def write():
    L('### 5.8 完整数据库架构（基于 MFGID 为最小追溯单位）')
    L('')
    L('**架构设计原则：**')
    L('')
    L('1. **批次层级管理**：Wafer Lot → Mother Lot → Sub Lot → Grade Lot → MFGID')
    L('2. **MFGID 为最小追溯单位**：Reel/Tape Level，ERP 财务核算基础')
    L('3. **批次与 MFGID 分离**：Lot 是管理单位，MFGID 是追溯单位')
    L('4. **完整追溯链**：从 MFGID 可以追溯到 Wafer Lot、工单、产品、客户')
    L('5. **Hold 维度扩展**：支持 9 种 Hold 维度（PO/WaferLot/Product/Package/Equipment/Step/Bin/Lot/Route）')
    L('')
    L('**表分类总览：**')
    L('')
    L('| 分类 | 表数量 | 说明 |')
    L('|------|--------|------|')
    L('| 系统基础表 | 7 | 部门、角色、用户、权限、签名等 |')
    L('| 主数据表 | 8 | 产品、路线、工序、设备、载具、配方等 |')
    L('| **来料管理表** | **3** | **Wafer Lot、Wafer Map、IQC 检验（新增）** |')
    L('| 批次管理表 | 1 | ProdLot（原有，需扩展字段） |')
    L('| MFGID 表 | 3 | MfgUnit、MfgOperationHistory、MfgPackTrace（新增） |')
    L('| Hold 管理表 | 2 | HoldRecord（扩展）、AutoHoldRule（新增） |')
    L('| 追溯链表 | 3 | LotTraceChain（新增）、LotSplit/Merge（原有） |')
    L('| 其他表 | 25 | 工单、步骤、操作历史、质量门、物料、报表等（原有） |')
    L('| **总计** | **51** | **新增 8 张，修改 2 张，删除 0 张** |')
    L('')
    L('#### 批次层级字段定义（ProdLot 表扩展）')
    L('')
    L('```sql')
    L('-- 批次层级：Wafer/Mother/Sub/Grade')
    L('ALTER TABLE `prod_lot` ADD COLUMN `lot_level` VARCHAR(20) DEFAULT \'Mother\'')
    L('  COMMENT \'批次层级：Wafer(来料), Mother(前道母批), Sub(后道子批), Grade(等级批次)\';')
    L('')
    L('-- 层级路径：完整追溯链')
    L('ALTER TABLE `prod_lot` ADD COLUMN `lot_hierarchy_path` VARCHAR(500) DEFAULT \'\'')
    L('  COMMENT \'层级路径：如 "WF-20260526-001/LOT-20260001/LOT-20260001-T1/LOT-20260001-GA"\';')
    L('')
    L('-- 根晶圆批次 ID')
    L('ALTER TABLE `prod_lot` ADD COLUMN `root_wafer_lot_id` VARCHAR(50) DEFAULT \'\'')
    L('  COMMENT \'根晶圆批次 ID: 始终指向最顶层的 Wafer Lot\';')
    L('')
    L('-- 工艺阶段：Assemble/Test/Finished')
    L('ALTER TABLE `prod_lot` ADD COLUMN `process_stage` VARCHAR(20) DEFAULT \'Assemble\'')
    L('  COMMENT \'工艺阶段：Assemble(前道), Test(后道), Finished(成品)\';')
    L('')
    L('-- 母批次 ID')
    L('ALTER TABLE `prod_lot` ADD COLUMN `mother_lot_id` VARCHAR(50) DEFAULT NULL')
    L('  COMMENT \'母批次 ID: Split 后子批指向母批\';')
    L('')
    L('-- 完成时间')
    L('ALTER TABLE `prod_lot` ADD COLUMN `completed_at` DATETIME NULL')
    L('  COMMENT \'完成时间：所有工序完成的时间\';')
    L('')
    L('-- 入库时间')
    L('ALTER TABLE `prod_lot` ADD COLUMN `in_warehouse_at` DATETIME NULL')
    L('  COMMENT \'入库时间：成品仓入库完成的时间\';')
    L('')
    L('-- 出货时间')
    L('ALTER TABLE `prod_lot` ADD COLUMN `shipped_at` DATETIME NULL')
    L('  COMMENT \'出货时间：MES 生命周期终点\';')
    L('')
    L('CREATE INDEX `idx_lot_level` ON `prod_lot`(`lot_level`);')
    L('CREATE INDEX `idx_root_wafer_lot` ON `prod_lot`(`root_wafer_lot_id`);')
    L('CREATE INDEX `idx_process_stage` ON `prod_lot`(`process_stage`);')
    L('```')
    L('')
    L('#### Hold 维度字段（HoldRecord 表扩展）')
    L('')
    L('```sql')
    L('-- Hold 范围：9 种维度')
    L('ALTER TABLE `prod_hold_record` ADD COLUMN `hold_scope` VARCHAR(20) DEFAULT \'Lot\'')
    L('  COMMENT \'Hold 范围：WorkOrder/WaferLot/Product/Package/Equipment/Step/Bin/Lot/Route\';')
    L('')
    L('-- 范围 ID')
    L('ALTER TABLE `prod_hold_record` ADD COLUMN `scope_id` VARCHAR(50) DEFAULT \'\'')
    L('  COMMENT \'范围 ID: 根据 HoldScope 存储对应的 ID (OrderId/WaferLotId/ProductId 等)\';')
    L('')
    L('-- Hold 优先级')
    L('ALTER TABLE `prod_hold_record` ADD COLUMN `hold_priority` INT DEFAULT 9')
    L('  COMMENT \'Hold 优先级：1(PO Hold) ~ 9(Lot Hold), 数字越小优先级越高\';')
    L('')
    L('-- 是否级联')
    L('ALTER TABLE `prod_hold_record` ADD COLUMN `is_cascade` TINYINT(1) DEFAULT 0')
    L('  COMMENT \'是否级联 Hold: 1=自动 Hold 关联批次，0=仅 Hold 当前批次\';')
    L('')
    L('CREATE INDEX `idx_hold_scope` ON `prod_hold_record`(`hold_scope`);')
    L('CREATE INDEX `idx_scope_id` ON `prod_hold_record`(`scope_id`);')
    L('CREATE INDEX `idx_hold_priority` ON `prod_hold_record`(`hold_priority`);')
    L('```')
    L('')
    L('#### 新增来料管理表（3 张）')
    L('')
    L('```sql')
    L('-- 3.1 来料晶圆批次表')
    L('CREATE TABLE `wafer_lot` (')
    L('  `wafer_lot_id` VARCHAR(50) PRIMARY KEY COMMENT \'来料批次号：WF-YYYYMMDD-NNN\',')
    L('  `wafer_id` VARCHAR(50) NOT NULL COMMENT \'晶圆 ID\',')
    L('  `wafer_fab` VARCHAR(100) DEFAULT \'\' COMMENT \'晶圆厂\',')
    L('  `wafer_size` VARCHAR(20) DEFAULT \'\' COMMENT \'晶圆尺寸：6inch/8inch/12inch\',')
    L('  `total_die_count` INT DEFAULT 0 COMMENT \'总 Die 数量\',')
    L('  `good_die_count` INT DEFAULT 0 COMMENT \'良品 Die 数量\',')
    L('  `product_id` VARCHAR(50) DEFAULT \'\' COMMENT \'产品 ID\',')
    L('  `order_id` VARCHAR(50) DEFAULT \'\' COMMENT \'关联工单号\',')
    L('  `status` VARCHAR(20) DEFAULT \'Received\' COMMENT \'状态：Received/Inspected/Released/Consumed\',')
    L('  `iqc_result` VARCHAR(20) DEFAULT \'\' COMMENT \'IQC 检验结果\',')
    L('  `iqc_inspector` VARCHAR(50) DEFAULT \'\' COMMENT \'IQC 检验员\',')
    L('  `iqc_inspected_at` DATETIME NULL COMMENT \'IQC 检验时间\',')
    L('  `released_at` DATETIME NULL COMMENT \'释放到生产的时间\',')
    L('  `consumed_at` DATETIME NULL COMMENT \'全部消耗完成时间\',')
    L('  `remark` VARCHAR(500) DEFAULT \'\' COMMENT \'备注\',')
    L('  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,')
    L('  `created_by` VARCHAR(50) DEFAULT \'\',')
    L('  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,')
    L('  `updated_by` VARCHAR(50) DEFAULT \'\'')
    L(') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;')
    L('')
    L('CREATE INDEX `idx_wafer_lot_status` ON `wafer_lot`(`status`);')
    L('CREATE INDEX `idx_wafer_lot_product` ON `wafer_lot`(`product_id`);')
    L('CREATE INDEX `idx_wafer_lot_order` ON `wafer_lot`(`order_id`);')
    L('')
    L('-- 3.2 Wafer Map 表')
    L('CREATE TABLE `wafer_map` (')
    L('  `map_id` VARCHAR(50) PRIMARY KEY COMMENT \'Map ID\',')
    L('  `wafer_lot_id` VARCHAR(50) NOT NULL COMMENT \'来料批次号\',')
    L('  `wafer_id` VARCHAR(50) NOT NULL COMMENT \'晶圆 ID\',')
    L('  `map_data` JSON COMMENT \'Map 数据：JSON 格式存储每个 Die 的坐标和状态\',')
    L('  `total_die` INT DEFAULT 0 COMMENT \'总 Die 数\',')
    L('  `good_die` INT DEFAULT 0 COMMENT \'良品 Die 数\',')
    L('  `bad_die` INT DEFAULT 0 COMMENT \'不良 Die 数\',')
    L('  `map_format` VARCHAR(20) DEFAULT \'\' COMMENT \'Map 格式：CSV/XML/JSON\',')
    L('  `imported_by` VARCHAR(50) DEFAULT \'\' COMMENT \'导入人\',')
    L('  `imported_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT \'导入时间\',')
    L('  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP')
    L(') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;')
    L('')
    L('CREATE INDEX `idx_wafer_map_lot` ON `wafer_map`(`wafer_lot_id`);')
    L('')
    L('-- 3.3 来料检验记录表')
    L('CREATE TABLE `incoming_inspection` (')
    L('  `inspection_id` VARCHAR(50) PRIMARY KEY COMMENT \'检验记录 ID\',')
    L('  `wafer_lot_id` VARCHAR(50) NOT NULL COMMENT \'来料批次号\',')
    L('  `inspection_type` VARCHAR(20) DEFAULT \'IQC\' COMMENT \'检验类型：IQC/IPQC/OQC\',')
    L('  `inspection_result` VARCHAR(20) DEFAULT \'\' COMMENT \'检验结果：Pass/Fail/Conditional\',')
    L('  `defect_code` VARCHAR(50) DEFAULT \'\' COMMENT \'缺陷代码\',')
    L('  `defect_description` VARCHAR(500) DEFAULT \'\' COMMENT \'缺陷描述\',')
    L('  `inspector_id` VARCHAR(50) DEFAULT \'\' COMMENT \'检验员 ID\',')
    L('  `inspector_name` VARCHAR(50) DEFAULT \'\' COMMENT \'检验员姓名\',')
    L('  `inspected_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT \'检验时间\',')
    L('  `remark` VARCHAR(500) DEFAULT \'\' COMMENT \'备注\',')
    L('  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP')
    L(') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;')
    L('')
    L('CREATE INDEX `idx_incoming_inspection_lot` ON `incoming_inspection`(`wafer_lot_id`);')
    L('```')
    L('')
    L('#### 新增 MFGID 表（3 张）')
    L('')
    L('```sql')
    L('-- 5.1 MFG 最小追溯单位表')
    L('CREATE TABLE `mfg_unit` (')
    L('  `mfg_id` VARCHAR(50) PRIMARY KEY COMMENT \'MFGID: 最小追溯单位唯一标识\',')
    L('  `lot_id` VARCHAR(50) NOT NULL COMMENT \'当前所属批次 ID\',')
    L('  `root_wafer_lot_id` VARCHAR(50) NOT NULL COMMENT \'根晶圆批次 ID\',')
    L('  `wafer_id` VARCHAR(50) DEFAULT \'\' COMMENT \'晶圆 ID\',')
    L('  `die_x` INT DEFAULT -1 COMMENT \'Die X 坐标\',')
    L('  `die_y` INT DEFAULT -1 COMMENT \'Die Y 坐标\',')
    L('  `serial_number` VARCHAR(50) DEFAULT \'\' COMMENT \'序列号\',')
    L('  `reel_id` VARCHAR(50) DEFAULT \'\' COMMENT \'卷带编号\',')
    L('  `reel_capacity` INT DEFAULT 0 COMMENT \'卷带容量\',')
    L('  `actual_qty` INT DEFAULT 0 COMMENT \'实际数量\',')
    L('  `status` VARCHAR(20) DEFAULT \'Created\' COMMENT \'状态：Created/Processing/Completed/Scrapped/Shipped\',')
    L('  `grade` VARCHAR(10) DEFAULT \'\' COMMENT \'等级：A/B/C\',')
    L('  `bin_result` VARCHAR(20) DEFAULT \'\' COMMENT \'Bin 结果\',')
    L('  `current_step` VARCHAR(50) DEFAULT \'\' COMMENT \'当前工序\',')
    L('  `rework_count` INT DEFAULT 0 COMMENT \'重工次数\',')
    L('  `pack_time` DATETIME NULL COMMENT \'包装时间\',')
    L('  `packed_by` VARCHAR(50) DEFAULT \'\' COMMENT \'包装操作员\',')
    L('  `box_id` VARCHAR(50) DEFAULT \'\' COMMENT \'绑定到的 Box ID\',')
    L('  `pallet_id` VARCHAR(50) DEFAULT \'\' COMMENT \'绑定到的 Pallet ID\',')
    L('  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,')
    L('  `completed_at` DATETIME NULL,')
    L('  `shipped_at` DATETIME NULL,')
    L('  INDEX `idx_lot_id` (`lot_id`),')
    L('  INDEX `idx_root_wafer_lot` (`root_wafer_lot_id`),')
    L('  INDEX `idx_status` (`status`),')
    L('  INDEX `idx_grade` (`grade`),')
    L('  INDEX `idx_reel_id` (`reel_id`)')
    L(') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;')
    L('')
    L('-- 5.2 MFG 操作历史表')
    L('CREATE TABLE `mfg_operation_history` (')
    L('  `history_id` VARCHAR(50) PRIMARY KEY,')
    L('  `mfg_id` VARCHAR(50) NOT NULL COMMENT \'MFGID\',')
    L('  `lot_id` VARCHAR(50) NOT NULL COMMENT \'批次 ID\',')
    L('  `step_code` VARCHAR(50) NOT NULL COMMENT \'工序代码\',')
    L('  `operation` VARCHAR(20) COMMENT \'操作：TrackIn/TrackOut/Hold/Release/Rework/Scrap\',')
    L('  `equipment_id` VARCHAR(50) DEFAULT \'\' COMMENT \'设备 ID\',')
    L('  `operator_id` VARCHAR(50) DEFAULT \'\' COMMENT \'操作员\',')
    L('  `result` VARCHAR(20) DEFAULT \'\' COMMENT \'结果：Pass/Fail\',')
    L('  `test_data` JSON COMMENT \'测试数据\',')
    L('  `remark` VARCHAR(500) DEFAULT \'\',')
    L('  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,')
    L('  INDEX `idx_mfg_id` (`mfg_id`),')
    L('  INDEX `idx_lot_id` (`lot_id`),')
    L('  INDEX `idx_step_code` (`step_code`)')
    L(') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;')
    L('')
    L('-- 5.3 MFG 包装追溯表')
    L('CREATE TABLE `mfg_pack_trace` (')
    L('  `pack_trace_id` VARCHAR(50) PRIMARY KEY,')
    L('  `mfg_id` VARCHAR(50) NOT NULL COMMENT \'MFGID\',')
    L('  `pack_level` VARCHAR(20) COMMENT \'包装层级：Unit/Reel/Box/Pallet\',')
    L('  `pack_id` VARCHAR(50) COMMENT \'包装 ID\',')
    L('  `parent_pack_id` VARCHAR(50) DEFAULT \'\' COMMENT \'父包装 ID\',')
    L('  `pack_qty` INT DEFAULT 0 COMMENT \'包装数量\',')
    L('  `packed_at` DATETIME DEFAULT CURRENT_TIMESTAMP,')
    L('  `packed_by` VARCHAR(50) DEFAULT \'\' COMMENT \'包装操作员\',')
    L('  INDEX `idx_mfg_id` (`mfg_id`),')
    L('  INDEX `idx_pack_id` (`pack_id`)')
    L(') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;')
    L('```')
    L('')
    L('#### 新增追溯链表（LotTraceChain）')
    L('')
    L('```sql')
    L('-- 7.1 批次追溯链表')
    L('CREATE TABLE `lot_trace_chain` (')
    L('  `chain_id` VARCHAR(50) PRIMARY KEY COMMENT \'追溯链 ID\',')
    L('  `child_lot_id` VARCHAR(50) NOT NULL COMMENT \'子批次 ID\',')
    L('  `parent_lot_id` VARCHAR(50) NOT NULL COMMENT \'父批次 ID\',')
    L('  `relation_type` VARCHAR(20) DEFAULT \'\' COMMENT \'关系类型：Split/Merge/GradeSplit/Rework/AssembleToTest\',')
    L('  `split_qty` INT DEFAULT 0 COMMENT \'拆分数量\',')
    L('  `merge_source_lot_ids` VARCHAR(500) DEFAULT \'\' COMMENT \'合并源批次 ID 列表\',')
    L('  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,')
    L('  `created_by` VARCHAR(50) DEFAULT \'\',')
    L('  INDEX `idx_child_lot` (`child_lot_id`),')
    L('  INDEX `idx_parent_lot` (`parent_lot_id`)')
    L(') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;')
    L('```')
    L('')
    L('#### 新增自动 Hold 规则表（AutoHoldRule）')
    L('')
    L('```sql')
    L('-- 6.2 自动 Hold 规则表')
    L('CREATE TABLE `auto_hold_rule` (')
    L('  `rule_id` VARCHAR(50) PRIMARY KEY COMMENT \'规则 ID\',')
    L('  `rule_name` VARCHAR(100) NOT NULL COMMENT \'规则名称\',')
    L('  `rule_type` VARCHAR(20) DEFAULT \'\' COMMENT \'规则类型：Yield/Equipment/Quality/Step\',')
    L('  `hold_scope` VARCHAR(20) DEFAULT \'Lot\' COMMENT \'Hold 范围\',')
    L('  `trigger_condition` JSON COMMENT \'触发条件：JSON 格式\',')
    L('  `hold_reason_code` VARCHAR(50) DEFAULT \'\' COMMENT \'Hold 原因代码\',')
    L('  `hold_reason` VARCHAR(500) DEFAULT \'\' COMMENT \'Hold 原因\',')
    L('  `auto_release` TINYINT(1) DEFAULT 0 COMMENT \'是否自动释放\',')
    L('  `auto_release_condition` JSON COMMENT \'自动释放条件\',')
    L('  `is_active` TINYINT(1) DEFAULT 1 COMMENT \'是否启用\',')
    L('  `priority` INT DEFAULT 5 COMMENT \'优先级：1-10\',')
    L('  `created_by` VARCHAR(50) DEFAULT \'\',')
    L('  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,')
    L('  `updated_by` VARCHAR(50) DEFAULT \'\',')
    L('  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,')
    L('  INDEX `idx_rule_type` (`rule_type`),')
    L('  INDEX `idx_active` (`is_active`)')
    L(') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;')
    L('```')
    L('')

    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    
    print(f'Generated: {OUTPUT_FILE}')
    print(f'Lines: {len(lines)}')

if __name__ == '__main__':
    write()
