#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
生成 MES 生产管理菜单改善方案 — 业务定义章节
"""

import os

OUTPUT_FILE = os.path.join(os.path.dirname(__file__), '..', 'mes_business_definition.md')

lines = []

def L(line=''):
    lines.append(line)

def write():
    L('## 二、半导体封装厂业务定义')
    L('')
    L('### 2.1 批次层级定义（Lot Hierarchy）')
    L('')
    L('```')
    L('半导体封装厂完整批次层级：')
    L('')
    L('┌─────────────────────────────────────────────────────────────────────────────────────────┐')
    L('│ 层级 1: Wafer Lot（来料晶圆批次）                                                        │')
    L('│   来源: 晶圆厂来料 / 客户来料 / 委外回料                                                  │')
    L('│   标识: WF-YYYYMMDD-NNN                                                                 │')
    L('│   属性: Wafer ID、晶圆厂、晶圆尺寸、Die 数量(Wafer Map)、来料检验结果                     │')
    L('│   状态: Received → Inspected → Released to Production                                    │')
    L('│   操作: 来料登记、IQC 检验、Wafer Map 导入                                               │')
    L('│                                                                                         │')
    L('│   ↓ 根据工单创建生产批次（1 片 Wafer = 1 个 Mother Lot）                                 │')
    L('│                                                                                         │')
    L('├─────────────────────────────────────────────────────────────────────────────────────────┤')
    L('│ 层级 2: Mother Lot（母批次 — Assemble 前道）                                             │')
    L('│   来源: Wafer Lot 拆分（1 Wafer Lot → N Mother Lots）                                   │')
    L('│   标识: LOT-YYYYNNNN（如 LOT-20260001）                                                  │')
    L('│   属性: 工单号、产品、封装类型、Route(Assemble)、原始数量、WaferLotId                     │')
    L('│   工序范围: DieAttach → WireBond → Mold → Cure → TrimForm → Marking → LaserMark         │')
    L('│          → VisualInspection → (Assemble 完成)                                           │')
    L('│   状态: Waiting → Processing → Hold → Completed(Assemble Done) → Scrapped               │')
    L('│   Split 规则: 允许在工序间（出站后）按数量拆分                                           │')
    L('│   Merge 规则: 允许同产品、同工序、同状态的批次合并                                       │')
    L('│                                                                                         │')
    L('│   ↓ Assemble 完成后进入 Test 阶段（可能再次拆分）                                        │')
    L('│                                                                                         │')
    L('├─────────────────────────────────────────────────────────────────────────────────────────┤')
    L('│ 层级 3: Sub Lot（子批次 — Test 后道）                                                    │')
    L('│   来源: Mother Lot 在 Assemble/Test 交接处拆分                                           │')
    L('│   标识: LOT-YYYYNNNN-TN 或 LOT-YYYYNNNN-SN（如 LOT-20260001-T1）                        │')
    L('│   属性: 继承 Mother Lot 所有属性 + Test Route + Bin 规格                                │')
    L('│   工序范围: CP Test → FT Test → BurnIn → FinalInspection → Packing                      │')
    L('│   状态: Waiting → Processing → Hold → Completed(Test Done) → Scrapped                   │')
    L('│   Split 规则: 允许按 Bin 结果拆分（Grade Split）                                         │')
    L('│   Merge 规则: 允许同 Bin 等级、同工序的批次合并                                          │')
    L('│                                                                                         │')
    L('│   ↓ Test 完成后按 Bin 等级拆分                                                           │')
    L('│                                                                                         │')
    L('├─────────────────────────────────────────────────────────────────────────────────────────┤')
    L('│ 层级 4: Grade Lot（等级批次 — 成品）                                                     │')
    L('│   来源: Sub Lot 按 Bin 结果拆分                                                          │')
    L('│   标识: LOT-YYYYNNNN-G{Grade}（如 LOT-20260001-GA）                                     │')
    L('│   属性: 继承 Sub Lot 所有属性 + Grade(A/B/C) + Bin 结果                                 │')
    L('│   状态: Completed → Shipped → InWarehouse                                                │')
    L('│   去向: 成品仓入库 → 客户交付                                                            │')
    L('│                                                                                         │')
    L('│   MES 生命周期终点: 成品仓入库完成（Shipped 后 MES 不再跟踪）                             │')
    L('└─────────────────────────────────────────────────────────────────────────────────────────┘')
    L('```')
    L('')
    L('### 2.2 Split/Merge 规则定义')
    L('')
    L('#### 2.2.1 Split（拆批）规则')
    L('')
    L('| 场景 | 是否允许 | 规则说明 |')
    L('|------|---------|---------|')
    L('| Wafer Lot → Mother Lot | ✅ 必须 | 来料晶圆按片拆分为 Mother Lot，1 Wafer = 1 Mother Lot。拆分时绑定 Wafer ID，记录 Die 数量（从 Wafer Map 读取） |')
    L('| Mother Lot → Sub Lot (Assemble→Test 交接) | ✅ 允许 | Assemble 完成后进入 Test 前，可按测试需求拆分。拆分后 Sub Lot 继承 Mother Lot 的 RouteId，但切换到 Test Route。需要记录 Assemble→Test 的交接信息 |')
    L('| 工序间拆分 (Mother Lot 内) | ✅ 允许 | 在工序出站后（Status=Waiting）可按数量拆分。条件: 批次状态为 Waiting/Released，不在 Processing 中。子批继承母批的 RouteId、CurrentStep、所有属性。子批 LotId = 母批 LotId + "-S" + 序号 |')
    L('| Grade Split (按 Bin 等级拆分) | ✅ 允许 | Test 完成后按 Bin 结果拆分为不同等级。条件: 批次已完成所有 Test 工序，有 Bin 结果。子批 LotId = 母批 LotId + "-G" + Grade(A/B/C)。拆分后母批状态变为 Completed，子批状态为 Waiting |')
    L('| Rework Split (不良品重工拆分) | ✅ 允许 | 发现不良品需要重工时，将不良部分拆出。条件: 批次在工序出站后，有明确的不良数量。子批进入重工路线(Rework Route)，母批继续正常路线。子批 LotId = 母批 LotId + "-R" + 重工次数 |')
    L('| Hold 拆分 (部分 Hold) | ✅ 允许 | 部分批次需要 Hold，部分继续生产时。条件: 批次状态为 Waiting/Released。Hold 部分拆出后状态变为 Hold，剩余部分继续生产 |')
    L('| ❌ Processing 中拆分 | ❌ 禁止 | 批次正在工序中加工（Status=Processing）时禁止拆分。原因: 数量不确定，无法保证追溯完整性 |')
    L('| ❌ Hold 状态拆分 | ❌ 禁止 | 批次被 Hold 时禁止拆分。原因: Hold 原因未解决前，不应改变批次结构 |')
    L('| ❌ Completed 后拆分 | ❌ 禁止 | 批次已完成所有工序后禁止拆分（Grade Split 除外）。原因: 成品批次结构已固定 |')
    L('| ❌ Scrapped 后拆分 | ❌ 禁止 | 已报废批次禁止任何操作 |')
    L('')
    L('#### 2.2.2 Merge（合批）规则')
    L('')
    L('| 场景 | 是否允许 | 规则说明 |')
    L('|------|---------|---------|')
    L('| 同工序合批 (Mother Lot 间) | ✅ 允许 | 同产品、同 Route、同工序、同状态的批次可以合并。条件: ProductId 相同、RouteId 相同、CurrentStepSeq 相同、Status 都是 Waiting、合批后数量不超载具容量。合并后保留所有源批次的追溯链 |')
    L('| Sub Lot 合批 (Test 阶段) | ✅ 允许 | Test 阶段同 Bin 等级的 Sub Lot 可以合并。条件: ProductId 相同、RouteId 相同、CurrentStepSeq 相同、BinResult 相同、Status 都是 Waiting |')
    L('| Rework 后合批 | ✅ 允许 | 重工完成的批次回到原工序后，可以与同工序批次合并。条件: ProductId 相同、RouteId 相同、CurrentStepSeq 相同、Status 都是 Waiting |')
    L('| ❌ 不同产品合批 | ❌ 禁止 | 不同 ProductId 的批次禁止合并。原因: 产品不同，无法保证质量追溯 |')
    L('| ❌ 不同 Route 合批 | ❌ 禁止 | 不同 RouteId 的批次禁止合并。原因: 工艺路线不同，后续工序无法统一 |')
    L('| ❌ 不同工序合批 | ❌ 禁止 | 不同 CurrentStepSeq 的批次禁止合并。原因: 工序进度不同，无法统一跟踪 |')
    L('| ❌ 不同 Bin 等级合批 | ❌ 禁止 | 不同 BinResult/Grade 的批次禁止合并。原因: 品质等级不同，混批会导致品质问题 |')
    L('| ❌ Hold 批次合批 | ❌ 禁止 | 被 Hold 的批次禁止参与合批。原因: Hold 原因未解决，不应与其他批次混合 |')
    L('| ❌ 超载具容量合批 | ❌ 禁止 | 合批后总数量超过载具最大容量时禁止合并。原因: 物理限制，载具无法容纳 |')
    L('')
    L('### 2.3 Hold 维度定义')
    L('')
    L('Hold 维度分类（按 Hold 范围从大到小）：')
    L('')
    L('| # | Hold 维度 | 范围 | 触发场景 | 影响 | 释放条件 | 权限 | 数据库字段 |')
    L('|---|----------|------|---------|------|---------|------|-----------|')
    L('| 1 | PO Hold（工单级） | 整个工单下所有批次 | 客户暂停、设计变更、物料问题、优先级调整 | 该工单下所有批次全部 Hold | 工单级别释放，所有批次自动恢复 | 生产主管/工程师 | `HoldScope="WorkOrder"`, `ScopeId=OrderId` |')
    L('| 2 | Wafer Lot Hold（来料级） | 同 WaferLotId 下所有批次 | 来料质量异常、晶圆厂通知问题、同批次多 Lot 相同异常 | 该 WaferLotId 下所有 Mother Lot 全部 Hold，新创建的也自动 Hold | IQC/品质工程师确认 | 品质工程师/主管 | `HoldScope="WaferLot"`, `ScopeId=WaferLotId` |')
    L('| 3 | Device Hold（产品级） | 特定 ProductId 所有在制批次 | 产品设计缺陷、客户投诉、可靠性测试异常、原材料变更 | 该 ProductId 下所有在制批次全部 Hold | 工程变更确认（ECO 完成）后释放 | 工程主管/品质主管 | `HoldScope="Product"`, `ScopeId=ProductId` |')
    L('| 4 | Package Hold（封装级） | 特定 PackageType 所有在制批次 | 封装材料异常、工艺参数异常、可靠性测试失败 | 该 PackageType 下所有在制批次全部 Hold | 封装工艺工程师确认 | 工艺工程师/主管 | `HoldScope="Package"`, `ScopeId=PackageType` |')
    L('| 5 | Equipment Hold（设备级） | 特定设备上正在加工或等待的所有批次 | 设备 Down/故障、参数偏移(SPC告警)、PM维护、Recipe验证失败 | 该设备 Processing 批次自动 Hold，Waiting 批次禁止进站 | 设备恢复运行、参数验证通过 | 设备工程师 | `HoldScope="Equipment"`, `ScopeId=EquipmentId` |')
    L('| 6 | Step Hold（工序级） | 特定 StepCode 所有在制批次 | 工序良率持续偏低、参数异常、操作人员资质问题 | 该工序所有在制批次 Hold，禁止新批次进站 | 工序验证通过后释放 | 工艺工程师/主管 | `HoldScope="Step"`, `ScopeId=StepCode` |')
    L('| 7 | Bin Hold（Bin 结果级） | 特定 BinResult 所有批次 | 某 Bin 码系统性问题、客户投诉特定等级、Bin 分选设备异常 | 该 BinResult 下所有批次 Hold | 测试工程师确认 | 测试/品质工程师 | `HoldScope="Bin"`, `ScopeId=BinResult` |')
    L('| 8 | Lot Hold（单批次级） | 单个 LotId | 工序良率低于阈值、外观检验异常、测试数据异常、重工超限 | 仅该批次 Hold | 根据 Hold 类型自动/手动释放 | 操作员发起，工程师/主管释放 | `HoldScope="Lot"`, `ScopeId=LotId` |')
    L('| 9 | Route Hold（工艺路线级） | 特定 RouteId 所有在制批次 | 工艺路线设计变更、路线验证失败 | 使用该 RouteId 的所有批次 Hold | 工艺路线验证通过后释放 | 工艺工程主管 | `HoldScope="Route"`, `ScopeId=RouteId` |')
    L('')
    L('**Hold 维度优先级**（当多个 Hold 同时存在时）：')
    L('')
    L('```')
    L('PO Hold > Wafer Lot Hold > Device Hold > Package Hold > Route Hold > Equipment Hold > Step Hold > Bin Hold > Lot Hold')
    L('```')
    L('')
    L('即：范围越大的 Hold 优先级越高，必须先释放大范围 Hold 才能释放小范围 Hold')
    L('')
    L('### 2.4 MES 生命周期边界定义')
    L('')
    L('```')
    L('MES 生命周期：从来料到成品仓入库')
    L('')
    L('阶段 1: 来料管理（Incoming）')
    L('  晶圆来料登记 → IQC 检验 → Wafer Map 导入 → 生成 Wafer Lot 编号 → 入库待产')
    L('  MES 关注点: 来料批次号、晶圆厂、晶圆 ID、Die 数量、来料检验结果、Wafer Map')
    L('  结束标志: Wafer Lot 状态变为 "Released to Production"')
    L('')
    L('  ↓ 根据工单创建生产批次')
    L('')
    L('阶段 2: 前道生产（Assemble / Front-End）')
    L('  DieAttach → WireBond → Mold → Cure → TrimForm → Marking → LaserMark → VisualInspection')
    L('  MES 关注点: 每道工序的进出站、数量、良率、设备、载具、Recipe、操作员')
    L('  可执行操作: Split（工序间）、Merge（同工序）、Hold（任意时刻）、Rework')
    L('  结束标志: 所有 Assemble 工序完成，批次状态变为 "Assemble Completed"')
    L('')
    L('  ↓ Assemble/Test 交接（可能再次拆分）')
    L('')
    L('阶段 3: 后道生产（Test / Back-End）')
    L('  CP Test → FT Test → BurnIn → FinalInspection → Packing')
    L('  MES 关注点: 测试数据、Bin 结果、良率、测试程序版本')
    L('  可执行操作: Split（按 Bin 等级）、Merge（同 Bin 等级）、Hold、Rework')
    L('  结束标志: 所有 Test 工序完成，批次状态变为 "Test Completed"')
    L('')
    L('  ↓ 按 Bin 等级拆分（Grade Split）')
    L('')
    L('阶段 4: 成品管理（Finished Goods）')
    L('  Grade Split → 生成 Grade Lot → 成品检验 → 成品入库 → 生成入库单')
    L('  MES 关注点: 等级分布（A/B/C 各多少）、最终良率、入库数量、入库时间')
    L('  结束标志: 成品仓入库完成，批次状态变为 "InWarehouse" → "Shipped"')
    L('')
    L('  ⚠️ MES 生命周期终点: 成品仓入库完成（Shipped）')
    L('     Shipped 后 MES 不再跟踪该批次，后续由 ERP/WMS 管理')
    L('```')
    L('')
    L('**生命周期状态机：**')
    L('')
    L('```')
    L('Created → Waiting → Processing → (循环: Processing ↔ Waiting) → Completed → InWarehouse → Shipped (MES 结束)')
    L('                 ↕')
    L('               Hold → Released → Waiting')
    L('                 ↕')
    L('               Scrapped (异常终止)')
    L('```')
    L('')
    L('### 2.5 批次层级与 Split/Merge 的关系矩阵')
    L('')
    L('```')
    L('批次层级关系图：')
    L('')
    L('  Wafer Lot (WF-20260526-001)')
    L('  │ 来料: 5 片晶圆, 每片 5000 Die')
    L('  │')
    L('  ├──→ Mother Lot 1 (LOT-20260001) ← Wafer #1, 5000 Die, Assemble Route')
    L('  │   │ DieAttach → WireBond → Mold → ... → VisualInspection (Assemble 完成)')
    L('  │   │')
    L('  │   ├──→ Sub Lot 1 (LOT-20260001-T1) ← 拆分进入 Test, 4900 Die (100 报废)')
    L('  │   │   │ CP Test → FT Test → BurnIn → FinalInspection → Packing (Test 完成)')
    L('  │   │   │')
    L('  │   │   ├──→ Grade Lot A (LOT-20260001-GA) ← Bin1, 4500 Die, Grade A (车规)')
    L('  │   │   ├──→ Grade Lot B (LOT-20260001-GB) ← Bin2, 300 Die, Grade B (工业)')
    L('  │   │   └──→ Grade Lot C (LOT-20260001-GC) ← Bin3, 100 Die, Grade C (消费)')
    L('  │   │')
    L('  │   └──→ Rework Lot (LOT-20260001-R1) ← WireBond 重工, 200 Die')
    L('  │       │ 重工路线: RW-WB-001 → 回到 WireBond → 继续正常路线')
    L('  │')
    L('  ├──→ Mother Lot 2 (LOT-20260002) ← Wafer #2, 5000 Die')
    L('  ├──→ Mother Lot 3 (LOT-20260003) ← Wafer #3, 5000 Die')
    L('  ├──→ Mother Lot 4 (LOT-20260004) ← Wafer #4, 5000 Die')
    L('  └──→ Mother Lot 5 (LOT-20260005) ← Wafer #5, 5000 Die')
    L('')
    L('追溯链示例：')
    L('  LOT-20260001-GA (Grade A 成品)')
    L('  ← MotherLotId: LOT-20260001')
    L('  ← WaferLotId: WF-20260526-001')
    L('  ← OrderId: WO-2026001')
    L('  ← 完整操作历史: 所有进出站记录')
    L('  ← 良率数据: 每道工序良率')
    L('  ← Hold 记录: 所有 Hold/释放记录')
    L('  ← 重工记录: 重工次数和原因')
    L('```')
    L('')
    L('### 2.6 当前方案需要补充的关键点')
    L('')
    L('| 模块 | 需要补充的内容 | 优先级 |')
    L('|------|---------------|--------|')
    L('| **批次管理** | 批次层级展示（Wafer Lot → Mother Lot → Sub Lot → Grade Lot） | P0 |')
    L('| | Split/Merge 规则引擎（9 项 Split 规则 + 7 项 Merge 规则） | P0 |')
    L('| | 追溯链可视化（完整批次血缘关系） | P0 |')
    L('| **Hold 管理** | 9 种 Hold 维度支持（PO/Wafer Lot/Device/Package/Equipment/Step/Bin/Lot/Route） | P0 |')
    L('| | Hold 维度优先级和级联释放 | P0 |')
    L('| | Hold 影响范围自动计算 | P0 |')
    L('| **工单管理** | 工单级 Hold（PO Hold） | P0 |')
    L('| | 工单与批次的层级关系展示 | P1 |')
    L('| **来料管理** | Wafer Lot 创建与管理（新增模块） | P0 |')
    L('| | Wafer Map 导入与 Die 数量计算 | P0 |')
    L('| **进站/出站** | 批次层级校验（Wafer Lot Hold 时禁止子批进站） | P0 |')
    L('| | 载具容量校验（合批时） | P0 |')
    L('| **拆批/合批** | 9 项 Split 规则校验 | P0 |')
    L('| | 7 项 Merge 规则校验 | P0 |')
    L('| | 追溯链自动建立 | P0 |')
    L('| **成品管理** | Grade Split 支持 | P0 |')
    L('| | 成品入库流程 | P0 |')
    L('| | MES 生命周期终点判定 | P0 |')
    L('| **数据库** | 新增 HoldScope 字段 | P0 |')
    L('| | 新增 LotLevel 字段 | P0 |')
    L('| | 新增 WaferMap 表 | P1 |')
    L('| | 新增 IncomingInspection 表 | P1 |')
    L('')

    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    
    print(f'Generated: {OUTPUT_FILE}')
    print(f'Lines: {len(lines)}')

if __name__ == '__main__':
    write()
