#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
生成 MES 数据库模型变更章节
"""

import os

OUTPUT_FILE = os.path.join(os.path.dirname(__file__), '..', 'mes_db_model_changes.md')

lines = []

def L(line=''):
    lines.append(line)

def write():
    L('## 五、数据库模型变更')
    L('')
    L('### 5.1 ProdLot 表新增字段')
    L('')
    L('```sql')
    L('-- ============================================================')
    L('-- 批次层级字段')
    L('-- ============================================================')
    L('')
    L('-- 批次层级: Wafer/Mother/Sub/Grade')
    L('ALTER TABLE `ProdLot` ADD COLUMN `LotLevel` VARCHAR(20) DEFAULT \'Mother\'')
    L('  COMMENT \'批次层级: Wafer(来料), Mother(前道母批), Sub(后道子批), Grade(等级批次)\';')
    L('')
    L('-- 层级路径: 完整追溯链')
    L('ALTER TABLE `ProdLot` ADD COLUMN `LotHierarchyPath` VARCHAR(500) DEFAULT \'\'')
    L('  COMMENT \'层级路径: 如 "WF-20260526-001/LOT-20260001/LOT-20260001-T1/LOT-20260001-GA"\';')
    L('')
    L('-- 根晶圆批次 ID')
    L('ALTER TABLE `ProdLot` ADD COLUMN `RootWaferLotId` VARCHAR(50) DEFAULT \'\'')
    L('  COMMENT \'根晶圆批次 ID: 始终指向最顶层的 Wafer Lot\';')
    L('')
    L('-- 工艺阶段: Assemble/Test')
    L('ALTER TABLE `ProdLot` ADD COLUMN `ProcessStage` VARCHAR(20) DEFAULT \'Assemble\'')
    L('  COMMENT \'工艺阶段: Assemble(前道), Test(后道), Finished(成品)\';')
    L('')
    L('-- Bin 结果')
    L('ALTER TABLE `ProdLot` ADD COLUMN `BinResult` VARCHAR(20) DEFAULT \'\'')
    L('  COMMENT \'Bin 结果: Bin1/Bin2/Bin3 或 Grade A/B/C\';')
    L('')
    L('-- 等级')
    L('ALTER TABLE `ProdLot` ADD COLUMN `Grade` VARCHAR(10) DEFAULT \'\'')
    L('  COMMENT \'等级: A(车规)/B(工业)/C(消费)\';')
    L('')
    L('-- 重工次数')
    L('ALTER TABLE `ProdLot` ADD COLUMN `ReworkCount` INT DEFAULT 0')
    L('  COMMENT \'重工次数\';')
    L('')
    L('-- 原始数量')
    L('ALTER TABLE `ProdLot` ADD COLUMN `OriginalQty` INT DEFAULT 0')
    L('  COMMENT \'原始数量: 拆分前的数量，用于追溯\';')
    L('')
    L('-- 完成时间')
    L('ALTER TABLE `ProdLot` ADD COLUMN `CompletedAt` DATETIME NULL')
    L('  COMMENT \'完成时间: 所有工序完成的时间\';')
    L('')
    L('-- 入库时间')
    L('ALTER TABLE `ProdLot` ADD COLUMN `InWarehouseAt` DATETIME NULL')
    L('  COMMENT \'入库时间: 成品仓入库完成的时间\';')
    L('')
    L('-- 创建索引')
    L('CREATE INDEX `idx_lot_level` ON `ProdLot`(`LotLevel`);')
    L('CREATE INDEX `idx_root_wafer_lot` ON `ProdLot`(`RootWaferLotId`);')
    L('CREATE INDEX `idx_process_stage` ON `ProdLot`(`ProcessStage`);')
    L('CREATE INDEX `idx_bin_result` ON `ProdLot`(`BinResult`);')
    L('CREATE INDEX `idx_grade` ON `ProdLot`(`Grade`);')
    L('```')
    L('')
    L('### 5.2 HoldRecord 表新增字段')
    L('')
    L('```sql')
    L('-- ============================================================')
    L('-- Hold 维度字段')
    L('-- ============================================================')
    L('')
    L('-- Hold 范围')
    L('ALTER TABLE `HoldRecord` ADD COLUMN `HoldScope` VARCHAR(20) DEFAULT \'Lot\'')
    L('  COMMENT \'Hold 范围: WorkOrder/WaferLot/Product/Package/Equipment/Step/Bin/Lot/Route\';')
    L('')
    L('-- 范围 ID')
    L('ALTER TABLE `HoldRecord` ADD COLUMN `ScopeId` VARCHAR(50) DEFAULT \'\'')
    L('  COMMENT \'范围 ID: 根据 HoldScope 存储对应的 ID (OrderId/WaferLotId/ProductId 等)\';')
    L('')
    L('-- Hold 优先级')
    L('ALTER TABLE `HoldRecord` ADD COLUMN `HoldPriority` INT DEFAULT 9')
    L('  COMMENT \'Hold 优先级: 1(PO Hold) ~ 9(Lot Hold), 数字越小优先级越高\';')
    L('')
    L('-- 是否级联')
    L('ALTER TABLE `HoldRecord` ADD COLUMN `IsCascade` TINYINT(1) DEFAULT 0')
    L('  COMMENT \'是否级联 Hold: 1=自动 Hold 关联批次, 0=仅 Hold 当前批次\';')
    L('')
    L('-- 释放人')
    L('ALTER TABLE `HoldRecord` ADD COLUMN `ReleasedBy` VARCHAR(50) DEFAULT \'\'')
    L('  COMMENT \'释放人 ID\';')
    L('')
    L('-- 释放时间')
    L('ALTER TABLE `HoldRecord` ADD COLUMN `ReleasedAt` DATETIME NULL')
    L('  COMMENT \'释放时间\';')
    L('')
    L('-- 释放原因')
    L('ALTER TABLE `HoldRecord` ADD COLUMN `ReleaseReason` VARCHAR(500) DEFAULT \'\'')
    L('  COMMENT \'释放原因\';')
    L('')
    L('-- 创建索引')
    L('CREATE INDEX `idx_hold_scope` ON `HoldRecord`(`HoldScope`);')
    L('CREATE INDEX `idx_scope_id` ON `HoldRecord`(`ScopeId`);')
    L('CREATE INDEX `idx_hold_priority` ON `HoldRecord`(`HoldPriority`);')
    L('```')
    L('')
    L('### 5.3 新增 WaferLot 表')
    L('')
    L('```sql')
    L('-- ============================================================')
    L('-- 来料晶圆批次表')
    L('-- ============================================================')
    L('')
    L('CREATE TABLE `WaferLot` (')
    L('  `WaferLotId` VARCHAR(50) PRIMARY KEY COMMENT \'来料批次号: WF-YYYYMMDD-NNN\',')
    L('  `WaferId` VARCHAR(50) NOT NULL COMMENT \'晶圆 ID\',')
    L('  `WaferFab` VARCHAR(100) DEFAULT \'\' COMMENT \'晶圆厂\',')
    L('  `WaferSize` VARCHAR(20) DEFAULT \'\' COMMENT \'晶圆尺寸: 6inch/8inch/12inch\',')
    L('  `TotalDieCount` INT DEFAULT 0 COMMENT \'总 Die 数量\',')
    L('  `GoodDieCount` INT DEFAULT 0 COMMENT \'良品 Die 数量(根据 Wafer Map)\',')
    L('  `ProductId` VARCHAR(50) DEFAULT \'\' COMMENT \'产品 ID\',')
    L('  `OrderId` VARCHAR(50) DEFAULT \'\' COMMENT \'关联工单号\',')
    L('  `Status` VARCHAR(20) DEFAULT \'Received\' COMMENT \'状态: Received/Inspected/Released/Consumed\',')
    L('  `IqcResult` VARCHAR(20) DEFAULT \'\' COMMENT \'IQC 检验结果: Pass/Fail/Pending\',')
    L('  `IqcInspector` VARCHAR(50) DEFAULT \'\' COMMENT \'IQC 检验员\',')
    L('  `IqcInspectedAt` DATETIME NULL COMMENT \'IQC 检验时间\',')
    L('  `ReleasedAt` DATETIME NULL COMMENT \'释放到生产的时间\',')
    L('  `ConsumedAt` DATETIME NULL COMMENT \'全部消耗完成时间\',')
    L('  `Remark` VARCHAR(500) DEFAULT \'\' COMMENT \'备注\',')
    L('  `CreatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP,')
    L('  `CreatedBy` VARCHAR(50) DEFAULT \'\',')
    L('  `UpdatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,')
    L('  `UpdatedBy` VARCHAR(50) DEFAULT \'\'')
    L(') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT=\'来料晶圆批次表\';')
    L('')
    L('CREATE INDEX `idx_wafer_lot_status` ON `WaferLot`(`Status`);')
    L('CREATE INDEX `idx_wafer_lot_product` ON `WaferLot`(`ProductId`);')
    L('CREATE INDEX `idx_wafer_lot_order` ON `WaferLot`(`OrderId`);')
    L('```')
    L('')
    L('### 5.4 新增 WaferMap 表')
    L('')
    L('```sql')
    L('-- ============================================================')
    L('-- Wafer Map 表')
    L('-- ============================================================')
    L('')
    L('CREATE TABLE `WaferMap` (')
    L('  `MapId` VARCHAR(50) PRIMARY KEY COMMENT \'Map ID\',')
    L('  `WaferLotId` VARCHAR(50) NOT NULL COMMENT \'来料批次号\',')
    L('  `WaferId` VARCHAR(50) NOT NULL COMMENT \'晶圆 ID\',')
    L('  `MapData` JSON COMMENT \'Map 数据: JSON 格式存储每个 Die 的坐标和状态\',')
    L('  `TotalDie` INT DEFAULT 0 COMMENT \'总 Die 数\',')
    L('  `GoodDie` INT DEFAULT 0 COMMENT \'良品 Die 数\',')
    L('  `BadDie` INT DEFAULT 0 COMMENT \'不良 Die 数\',')
    L('  `MapFormat` VARCHAR(20) DEFAULT \'\' COMMENT \'Map 格式: CSV/XML/JSON\',')
    L('  `ImportedBy` VARCHAR(50) DEFAULT \'\' COMMENT \'导入人\',')
    L('  `ImportedAt` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT \'导入时间\',')
    L('  `CreatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP')
    L(') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT=\'Wafer Map 表\';')
    L('')
    L('CREATE INDEX `idx_wafer_map_lot` ON `WaferMap`(`WaferLotId`);')
    L('```')
    L('')
    L('### 5.5 新增 IncomingInspection 表')
    L('')
    L('```sql')
    L('-- ============================================================')
    L('-- 来料检验记录表')
    L('-- ============================================================')
    L('')
    L('CREATE TABLE `IncomingInspection` (')
    L('  `InspectionId` VARCHAR(50) PRIMARY KEY COMMENT \'检验记录 ID\',')
    L('  `WaferLotId` VARCHAR(50) NOT NULL COMMENT \'来料批次号\',')
    L('  `InspectionType` VARCHAR(20) DEFAULT \'IQC\' COMMENT \'检验类型: IQC/IPQC/OQC\',')
    L('  `InspectionResult` VARCHAR(20) DEFAULT \'\' COMMENT \'检验结果: Pass/Fail/Conditional\',')
    L('  `DefectCode` VARCHAR(50) DEFAULT \'\' COMMENT \'缺陷代码\',')
    L('  `DefectDescription` VARCHAR(500) DEFAULT \'\' COMMENT \'缺陷描述\',')
    L('  `InspectorId` VARCHAR(50) DEFAULT \'\' COMMENT \'检验员 ID\',')
    L('  `InspectorName` VARCHAR(50) DEFAULT \'\' COMMENT \'检验员姓名\',')
    L('  `InspectedAt` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT \'检验时间\',')
    L('  `Remark` VARCHAR(500) DEFAULT \'\' COMMENT \'备注\',')
    L('  `CreatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP')
    L(') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT=\'来料检验记录表\';')
    L('')
    L('CREATE INDEX `idx_incoming_inspection_lot` ON `IncomingInspection`(`WaferLotId`);')
    L('```')
    L('')
    L('### 5.6 新增 LotTraceChain 表')
    L('')
    L('```sql')
    L('-- ============================================================')
    L('-- 批次追溯链表')
    L('-- ============================================================')
    L('')
    L('CREATE TABLE `LotTraceChain` (')
    L('  `ChainId` VARCHAR(50) PRIMARY KEY COMMENT \'追溯链 ID\',')
    L('  `ChildLotId` VARCHAR(50) NOT NULL COMMENT \'子批次 ID\',')
    L('  `ParentLotId` VARCHAR(50) NOT NULL COMMENT \'父批次 ID\',')
    L('  `RelationType` VARCHAR(20) DEFAULT \'\' COMMENT \'关系类型: Split/Merge/GradeSplit/Rework/AssembleToTest\',')
    L('  `SplitQty` INT DEFAULT 0 COMMENT \'拆分数量\',')
    L('  `MergeSourceLotIds` VARCHAR(500) DEFAULT \'\' COMMENT \'合并源批次 ID 列表(逗号分隔)\',')
    L('  `CreatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP,')
    L('  `CreatedBy` VARCHAR(50) DEFAULT \'\'')
    L(') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT=\'批次追溯链表\';')
    L('')
    L('CREATE INDEX `idx_trace_child` ON `LotTraceChain`(`ChildLotId`);')
    L('CREATE INDEX `idx_trace_parent` ON `LotTraceChain`(`ParentLotId`);')
    L('```')
    L('')
    L('### 5.7 新增 AutoHoldRule 表')
    L('')
    L('```sql')
    L('-- ============================================================')
    L('-- 自动 Hold 规则表')
    L('-- ============================================================')
    L('')
    L('CREATE TABLE `AutoHoldRule` (')
    L('  `RuleId` VARCHAR(50) PRIMARY KEY COMMENT \'规则 ID\',')
    L('  `RuleName` VARCHAR(100) NOT NULL COMMENT \'规则名称\',')
    L('  `RuleType` VARCHAR(20) DEFAULT \'\' COMMENT \'规则类型: Yield/Equipment/Quality/Step\',')
    L('  `HoldScope` VARCHAR(20) DEFAULT \'Lot\' COMMENT \'Hold 范围: Lot/Step/Equipment/Product\',')
    L('  `TriggerCondition` JSON COMMENT \'触发条件: JSON 格式\',')
    L('  `HoldReasonCode` VARCHAR(50) DEFAULT \'\' COMMENT \'Hold 原因代码\',')
    L('  `HoldReason` VARCHAR(500) DEFAULT \'\' COMMENT \'Hold 原因\',')
    L('  `AutoRelease` TINYINT(1) DEFAULT 0 COMMENT \'是否自动释放: 1=是, 0=否\',')
    L('  `AutoReleaseCondition` JSON COMMENT \'自动释放条件: JSON 格式\',')
    L('  `IsActive` TINYINT(1) DEFAULT 1 COMMENT \'是否启用\',')
    L('  `Priority` INT DEFAULT 5 COMMENT \'优先级: 1-10\',')
    L('  `CreatedBy` VARCHAR(50) DEFAULT \'\',')
    L('  `CreatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP,')
    L('  `UpdatedBy` VARCHAR(50) DEFAULT \'\',')
    L('  `UpdatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP')
    L(') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT=\'自动 Hold 规则表\';')
    L('')
    L('CREATE INDEX `idx_auto_hold_rule_type` ON `AutoHoldRule`(`RuleType`);')
    L('CREATE INDEX `idx_auto_hold_rule_active` ON `AutoHoldRule`(`IsActive`);')
    L('```')
    L('')

    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    
    print(f'Generated: {OUTPUT_FILE}')
    print(f'Lines: {len(lines)}')

if __name__ == '__main__':
    write()
